services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: agentopsynvectorbase
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: strongpassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: next_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:
